Finalising SRS and readme for Demo 1
COS301-SE-2024/Crop-Prediction-System pull request #14
Opened 2024-05-30 21:59 UTC by iwandejong

Please review the PDF in particular

2024-05-31 06:32 UTC, Xavier893 requested changes
- Class Diagram of System is needed for SRS.
- Will confirm about the use case diagrams, but I think one use case diagram per use case implemented is needed
- Third use case for CRUD needed

2024-05-31 14:57 UTC, iwandejong commented
> * Class Diagram of System is needed for SRS.
> 
>     * Will confirm about the use case diagrams, but I think one use case diagram per use case implemented is needed
> 
>     * Third use case for CRUD needed

Changes have been made. Please review

2024-05-31 21:53 UTC, Tiaan2 approved these changes

2024-06-01 10:56 UTC, iwandejong commented
- Added problem statement to introduction
- Added service contracts outlining the functional requirements
- Added descriptions to the Backend Class Diagram to mention Design Patterns
- Made Architectural Pattern more generic (excluded technologies used)

2024-06-03 07:27 UTC, Xavier893 approved these changes

2024-06-03 07:27 UTC, merged